#ifndef AEGIS_CLI_H
#define AEGIS_CLI_H

#define AEGIS_CLI_VERSION "0.1.0"

typedef enum {
    AEGIS_CLI_EXIT_SUCCESS = 0,
    AEGIS_CLI_EXIT_GENERAL = 1,
    AEGIS_CLI_EXIT_USAGE = 2,
    AEGIS_CLI_EXIT_CONFIG = 3,
    AEGIS_CLI_EXIT_PROFILE = 4,
    AEGIS_CLI_EXIT_PROVIDER = 5,
    AEGIS_CLI_EXIT_TOOL = 6,
    AEGIS_CLI_EXIT_POLICY = 7,
    AEGIS_CLI_EXIT_APPROVAL = 8,
    AEGIS_CLI_EXIT_WORKSPACE = 9,
    AEGIS_CLI_EXIT_MAX_STEPS = 10,
    AEGIS_CLI_EXIT_STATE = 11,
    AEGIS_CLI_EXIT_TRACE = 12,
    AEGIS_CLI_EXIT_EVAL = 13,
    AEGIS_CLI_EXIT_INTERRUPTED = 130
} AegisCliExitCode;

int aegis_cli_main(int argc, char **argv);

#endif
